target 'GIFKit', :exclusive => true do
  pod "GIFKit", :path => "../"
  pod "FLAnimatedImage", :git => "https://github.com/geoffmacd/FLAnimatedImage.git"
end

target 'Tests', :exclusive => true do
  pod "GIFKit", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
